nextest-rs/nextest

- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- site/src/CHANGELOG.md
Stops lots of little syscalls from happening.
Fixes #35.
> [cargo-nextest] add a BufWriter around reporter writes

- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
This commit updates cargo-nextest to 3.1.0, and replaces the deprecated `help_heading` in the clap attributes with its replacement: `next_help_heading`.
#54 and #55 individually also update clap and clap_derive (lock only) from 3.0.14 to 3.1.0. Since `RUSTFLAGS=-D warnings` is used however, their GitHub actions pipelines fail, because `-D warnings` implies use of deprecated functions are not allowed.
While already stated in the Apache license, I will explicitly agree that my contributions will be dual-licensed under the terms of the [`LICENSE-MIT`](https://github.com/nextest-rs/nextest/blob/e4d2431c10f05fe9f6e9397aaeecee9d6503dd91/LICENSE-MIT) and [`LICENSE-APACHE`](https://github.com/nextest-rs/nextest/blob/e4d2431c10f05fe9f6e9397aaeecee9d6503dd91/LICENSE-APACHE) files in the root …
> Update clap from 3.0.14 to 3.1.0

- Cargo.lock
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- fixtures/nextest-tests/.cargo/config
- fixtures/passthrough
- nextest-runner/Cargo.toml
- nextest-runner/src/errors.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/src/test_list.rs
- nextest-runner/tests/basic.rs
- nextest-runner/tests/target_runner.rs
This adds support for [target runners](https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner) which allows nextest to run tests for binaries that can't execute natively on the host such in cross-compilation situations targeting `x86_64-pc-windows-msvc` from a Linux host, or `wasm32-unknown-unknown`, etc.
This PR supports both the `CARGO_TARGET_{TRIPLE}_RUNNER` environment variable, as well as reading configured runners from `.cargo/config.toml`. This currently respects the same (IMO broken) [behavior](https://github.com/rust-lang/cargo/issues/2930) in cargo for looking up the hierarchy of configs.
Example output running windows binaries via wine from linux
Resolves: #57
> Add support for target runners

- cargo-nextest/src/dispatch.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/target_runner.rs
Fix for https://github.com/nextest-rs/nextest/issues/73
I'm not sure about the second commit. Maybe we should stop the ancestors walk at the workspace root ?
What was the goal behind `use_cargo_home` ? tests ? If so, I guess both approach would work.
Fun fact: the tests where broken before the first commit on my computer because they were reading my home config with an array of strings (even with the `use_cargo_home = false`)...
> Improve runner parsing

- fixtures/nextest-tests/Cargo.toml
- fixtures/nextest-tests/examples/nextest-tests.rs
- fixtures/nextest-tests/examples/other.rs
- fixtures/nextest-tests/src/bin/nextest-tests.rs
- fixtures/nextest-tests/src/bin/other.rs
- fixtures/nextest-tests/src/main.rs
- fixtures/nextest-tests/tests/other.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/test_list.rs
- nextest-runner/tests/integration/fixtures.rs
In a crate with multiple targets that have the same name as the package, if both have tests, tests from one of the targets will be missing from the JSON output. I ran into this is in a lib + bin package. You can see a minimal example [here](https://github.com/pmsanford/nextest-json-suite-overwrite).
This is because of the way `RustTestArtifact.binary_id` is constructed. Currently, if the target name is equal to the package name, the package name is taken as the `binary_id`. There are cases (such as lib + bin) where two targets will have the same name as the package name. This results in `binary_id` being non-unique in those cases, and the doc comment for `binary_id` says it should be unique. Currently this only seems to affect the JSON output of the list command - the human readable …
> Add artifact kind to binary_id if it's not 'lib'

- cargo-nextest/src/cargo_cli.rs
`CargoCli::all_args()` is used in `TestBuildFilter::compute()`
https://github.com/nextest-rs/nextest/blob/4d8c9200bc3415b38debb2084ce6c4a45bf1d18a/cargo-nextest/src/dispatch.rs#L210
> [cargo-nextest] remove allow attribute

- fixtures/passthrough
- nextest-runner/Cargo.toml
- nextest-runner/test-helpers/passthrough.rs
- nextest-runner/tests/integration/target_runner.rs
Using a shell script causes issues on macOS because of SIP. See
#84 for more.
> [nextest-runner] bring our own passthrough test binary

- fixtures/nextest-tests/Cargo.toml
- fixtures/nextest-tests/derive/Cargo.toml
- fixtures/nextest-tests/derive/src/lib.rs
- nextest-runner/tests/integration/fixtures.rs
Adding a proc-macro lib in the workspace used as tests input makes `nextest-runner::integration target_runner::run::test_run_with_target_runner` fail on MacOS.
I'm not yet sure why.
> Add proc-macro lib in tests fixtures

- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- cargo-nextest/src/lib.rs
- cargo-nextest/src/main.rs
- cargo-nextest/src/output.rs
- cargo-nextest/src/tests_integration/fixtures.rs
- cargo-nextest/src/tests_integration/mod.rs
- cargo-nextest/src/tests_integration/temp_project.rs
- nextest-metadata/src/exit_codes.rs
- nextest-metadata/src/test_list.rs
- nextest-runner/src/test_list.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- site/src/book/reusing-build.md
Implements https://github.com/nextest-rs/nextest/issues/44
This is still work in progress, but I just wanted to be sure I was on the right tracks from your point of view.
I have the basic feature working:
```sh
> cargo nextest list-bins --message-format json > binaries.json
> cargo nextest run --test-list binaries.json
```
Still to do:
At the moment, I'm still creating the graph when running, I'm wondering if I should save it (or at least the needed part). This could allow me to use the runner without `cargo`  installed (which could be great for my use case, but not indispensable for the moment).
> Adds support for separated build and run

- cargo-nextest/src/cargo_cli.rs
`binaries-metadata` is the main entry point of ReuseBuildOpts, so using it as the conflicting argument.
I hopped to be able to have less duplication, but didn't find a good way of doing it. I opened a discussion about this: https://github.com/clap-rs/clap/discussions/3563
> Make CargoOptions conflict with ReuseBuildOpts

- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/output.rs
- cargo-nextest/src/reuse_build.rs
Enable clap env feature to use env attribute api.
CargoOption has not changed.
https://github.com/nextest-rs/nextest/issues/21
> [cargo-nextest] read configuration as environment variables

- .github/workflows/ci.yml
- Cargo.lock
- README.md
- cargo-nextest/Cargo.toml
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/reuse_build.rs
- cargo-nextest/src/tests_integration/fixtures.rs
- cargo-nextest/src/tests_integration/mod.rs
- cargo-nextest/src/tests_integration/temp_project.rs
- nextest-metadata/Cargo.toml
- nextest-metadata/README.md
- nextest-metadata/src/lib.rs
- nextest-metadata/src/test_list.rs
- nextest-runner/CHANGELOG.md
- nextest-runner/Cargo.toml
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- quick-junit/CHANGELOG.md
- quick-junit/Cargo.toml
- quick-junit/README.md
- quick-junit/src/lib.rs
This is required because `binaries-dir-remap` is insufficient to model
situations with shared libraries (https://github.com/nextest-rs/nextest/issues/82).
As part of this, we're going to change the reuse-build instructions to
recommend archiving the entire target directory. In the future, we may
be able to build a better archiving tool into nextest.
> [cargo-nextest] change binaries-dir-remap to target-dir-remap

- Cargo.lock
- nextest-filtering/Cargo.toml
- nextest-filtering/examples/parser.rs
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/unicode_string.rs
- site/src/book/filtering-expression.md
Fix for #144
- Adds the `/` for regex
- Removes the whitespace escaping from unicode string
- Adds a small example for quick manual filtering expression parsing test
> Add `/` escaping in regex, remove useless whitespace escaping in unicode string

- README.md
Small fix in the root README. the badge was not showing the right version number.
> Fix nextest-filtering badge version

- nextest-runner/src/test_filter.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/target_runner.rs
Test filtering was misbehaving when expression filters were present but
name filters weren't.
> [nextest-runner] fix expression/name filtering

- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/tests_integration/fixtures.rs
- cargo-nextest/src/tests_integration/mod.rs
- fixtures/nextest-tests/benches/my-bench.rs
- fixtures/nextest-tests/cdylib/cdylib-example/Cargo.toml
- fixtures/nextest-tests/cdylib/cdylib-example/src/lib.rs
- fixtures/nextest-tests/src/bin/nextest-tests.rs
- fixtures/nextest-tests/src/lib.rs
- fixtures/nextest-tests/tests/basic.rs
- nextest-metadata/src/test_list.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
If paths are remapped, the compile-time CARGO_BIN_EXE_ environment
variables are no longer valid. Set these NEXTEST_ replacement variables
instead.
> [nextest-runner] expose NEXTEST_BIN_EXE_ environment variables at runtime

- Cargo.lock
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- cargo-nextest/src/reuse_build.rs
- cargo-nextest/src/tests_integration/mod.rs
- nextest-metadata/src/exit_codes.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/errors.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reuse_build/archive_reporter.rs
- nextest-runner/src/reuse_build/archiver.rs
- nextest-runner/src/reuse_build/mod.rs
- nextest-runner/src/reuse_build/unarchiver.rs
- nextest-runner/tests/integration/fixtures.rs
- workspace-hack/Cargo.toml
> add support for creating and using archives

- cargo-nextest/src/tests_integration/mod.rs
- fixtures/nextest-tests/cdylib/cdylib-link/build.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/reuse_build/archiver.rs
This is a bit annoying: some libraries like grpcio-sys 1.1.8 produce
paths that don't exist. Ignore them.
Closes #247.
> [nextest-runner] skip over missing linked paths

- cargo-nextest/src/dispatch.rs
- nextest-runner/default-config.toml
- nextest-runner/src/config.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
This is useful as an intermediate step between printing nothing and full
stdout/stderr.
Closes #255.
> [nextest-runner] add the ability to print out status lines at the end of a test run

- cargo-nextest/src/dispatch.rs
- nextest-runner/src/cargo_config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/target_runner.rs
* Replicate the default value of `DYLD_FALLBACK_LIBRARY_PATH` done by Cargo.
* We're going to discover `build.target` the same way Cargo does -- factor out the search done for the target runner.
> [nextest-runner] some more fixes + prep for storing sysroots

- .config/nextest.toml
- cargo-nextest/src/dispatch.rs
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/stopwatch.rs
* Improve the `final-status-level` option by reordering it slightly (skip is prioritized over pass) and printing out slow and flaky tests clearly.
* produce round numbers for SLOW lines
* add a separator line before the `Summary` line.
Closes #270.
> some improvements to the nextest reporter

- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
Adding partial support for specifying test binary arguments like cargo. It can
greatly simplify the transitioning from cargo to nextest.
Signed-off-by: tabokie <xy.tao@outlook.com>
> support passing filter as test binary arguments

- Cargo.lock
- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/tests/segfault.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
Print out these lines as "ABRT SIG N" where N is the signal received.
Also recognize common signals SIGINT and SIGSEGV.
Closes #281.
> [nextest-runner] add detection for signals

- nextest-runner/src/list/test_list.rs
Signed-off-by: tabokie <xy.tao@outlook.com>
Last I checked this behavior is consistent with cargo test. Bench cases that appear in test binary list should be considered a normal test.
> treat benchmarks as normal tests

- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/benches/my-bench.rs
- nextest-runner/tests/integration/fixtures.rs
Test out the new capability to test benchmarks, added in #283.
RUSTC_BOOTSTRAP is required to test this out, but we're not using it in
any production code.
> [fixtures] add a #[bench] fixture

- Cargo.lock
- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/.config/nextest.toml
- fixtures/nextest-tests/tests/basic.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
In order:
1. The signal the test failed with, if any.
2. Stack trace from stderr.
3. "note: test did not panic as expected" from stdout.
Closes #311.
> [nextest-runner] heuristically extract description for JUnit output

- .config/nextest.toml
- Cargo.lock
- cargo-nextest/src/dispatch.rs
- nextest-runner/Cargo.toml
- nextest-runner/default-config.toml
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/runner.rs
Support:
* an integer
* the string `"num-cpus"`
Closes #319.
> [nextest-runner] add support for test-threads config option

- cargo-nextest/Cargo.toml
Supports #31.
Tested local install with target `x86_64-unknown-linux-gnu`. I also verified via dry-run the URLs for a few more targets:
* `x86_64-unknown-linux-gnu` -> https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.23/cargo-nextest-0.9.23-x86_64-unknown-linux-gnu.tar.gz
* `x86_64-apple-darwin` ->  https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.23/cargo-nextest-0.9.23-universal-apple-darwin.tar.gz
* `aarch64-apple-darwin` -> https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.23/cargo-nextest-0.9.23-universal-apple-darwin.tar.gz
* `x86_64-pc-windows-msvc` -> https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.23/cargo-nextest-0.9.23-x86_64-pc-windows-msvc.tar.gz
Credit goes to @sunshowers for …
> Add metadata for cargo-binstall

- .config/nextest.toml
These tests started being flaky on Windows a couple of days ago -- see
e.g.
https://github.com/nextest-rs/nextest/runs/7312274373?check_suite_focus=true.
The tests appear to work fine in local environments.
> [ci] retry integration tests a few times

- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/.config/nextest.toml
- fixtures/nextest-tests/tests/basic.rs
- nextest-runner/src/config.rs
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
Support per-test overrides for `slow-timeout`.
> [nextest-runner] support slow-timeout overrides

- .config/nextest.toml
- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/tests/basic.rs
- nextest-runner/Cargo.toml
- nextest-runner/default-config.toml
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/signal.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
- workspace-hack/Cargo.toml
Switch to tokio for the main runner loop so we get the ability to select across pipe reads and timeouts.
Use this to detect and handle tests which spawn subprocesses that leak handles. We treat them as passing tests for now, though might make leak failures configurable in the future.
Note that we can only detect subprocesses which inherit standard input/output/error. We can't detect subprocesses spawned with piped stdio that outlive the process. That's a far more challenging problem (see duct's [gotchas.md](https://github.com/oconnor663/duct.py/blob/master/gotchas.md#killing-grandchild-processes) for more). However this solves the immediate problem of nextest hanging because of unclosed pipes, and is probably the most common set of issues.
TODO:
Closes #15.
> detect tests that spawn subprocesses which leak handles

- cargo-nextest/src/dispatch.rs
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
Add an option for tools that integrate with nextest to specify configs
that are lower than .config/nextest.toml in priority, but higher than
the default config.
An example of a tool that would benefit from this is https://github.com/saethlin/miri-tools; see https://github.com/rust-lang/miri/pull/2398#issuecomment-1190903374.
> [nextest-runner] add a --tool-config-file option

- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
Config overrides should add onto each other, not replace each other.
This also provides better attribution for error messages.
Fixes #384.
> [nextest-runner] make config overrides additive

- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/signal.rs
This allows for a process and all its child processes to be signaled
atomically.
A child process spawned by a test can choose to run in another process
group, but that's quite uncommon.
The one regression with process groups is that if you press Ctrl-C, tests no longer
exit. In the second commit we fix those regressions by forwarding Ctrl-C (and also SIGTERM/SIGHUP) to child process groups.
This should address https://github.com/rust-lang/miri/issues/2421 on Unix. Going to do a similar patch on Windows as well.
> [nextest-runner] put each test into a process group on unix

- Cargo.lock
- cargo-nextest/src/tests_integration/fixtures.rs
- fixtures/nextest-tests/tests/basic.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- workspace-hack/Cargo.toml
A job object allows us to atomically kill all child processes within a test.
There are some race conditions involved here, so we ignore errors -- job objects are a best-effort thing for us.
> [nextest-runner] use job objects for process management on Windows

- .github/workflows/release.yml
- site/src/book/release-urls.md
Fixes https://github.com/nextest-rs/nextest/issues/392.
@sunshowers thanks for sharing the link to the playground, it was very helpful. I did experiment with it, and I _think_ this should build the binaries correctly, but I'm not 100% sure.
> Build binaries for Linux aarch64 on CI.

- .github/workflows/release.yml
- site/src/book/release-urls.md
I can confirm that [it compiles for Linux musl target](https://github.com/messense/nextest/runs/7488680242?check_suite_focus=true).
Closes #391
> Add x86_64-unknown-linux-musl binary release

- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- nextest-runner/src/cargo_config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/target_runner.rs
- nextest-runner/tests/integration/target_triple.rs
Follow the same rules that Cargo does:
* configs form valid TOML files
* hierarchical config: env vars over CLI options
* configs followed from left to right
Tested against Miri past https://github.com/rust-lang/miri/pull/2428.
Closes #400.
cc @saethlin
> [nextest-runner] parse CLI configs passed in via --config

- .github/workflows/release.yml
- nextest-runner/src/lib.rs
We're going to remove this hack once Rust 1.64 is stabilized.
> [nextest-runner] add process-group hack to regain performance

- Cargo.lock
- fixtures/nextest-tests/Cargo.lock
- fixtures/nextest-tests/Cargo.toml
- fixtures/nextest-tests/tests/basic.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/runner.rs
This implements a `NEXTEST_RUN_ID` as proposed in #416.
Refs https://github.com/mitsuhiko/insta/issues/242
> Implement NEXTEST_RUN_ID env-var to identify runs

- .github/workflows/coverage.yml
Looks like stable Rust now has support for llvm-cov.
> [ci] update coverage job to use stable

- .github/workflows/release.yml
- site/src/book/pre-built-binaries.md
- site/src/book/release-urls.md
Closes #419
- Site: Add latest pre-built link for `x86_64-unknown-linux-musl`
- Release: Add pre-build for `i686-pc-windows-msvc`
- Site: Add info and links for pre-built for `i686-pc-windows-msvc`
> Add i686-pc-windows-msvc in release workflow

- nextest-runner/src/runner.rs
Signed-off-by: Alex Chi <iskyzh@gmail.com>
Currently, a test will still be retried even if nextest receives a cancel signal. This PR fixes this behavior by not retrying after cancelled. To reproduce this issue, press Ctrl+C immediately after `cargo nextest run` with the following config and test crate:
nextest.toml:
```toml
[profile.default]
retries = 5
slow-timeout = { period = "5s" }
status-level = "all"
final-status-level = "slow"
```
lib.rs:
```rust
#[cfg(test)]
mod tests {
#[test]
fn test_timeout() {
println!("test");
std::thread::sleep(std::time::Duration::from_secs(10));
println!("test");
}    
}
```
> fix(runner): cancel retry if cancel signal is received

- Cargo.lock
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/cargo_config.rs
- nextest-runner/src/errors.rs
Rust 1.63 stabilizes `--config` with a few changes: https://github.com/rust-lang/cargo/pull/10755
Mirror those changes into nextest.
> [nextest-runner] support changes to CLI config options added in Rust 1.63

- cargo-nextest/src/dispatch.rs
- nextest-metadata/src/test_list.rs
- nextest-runner/src/cargo_config.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
Fixes #468 
Previously `CARGO_TARGET_<target>_RUNNER` would be ignored if a build was
loaded from an archive file with --archive, because no/the incorrect target-triple was
detected in that case.
This patch changes the runner detection to account for those cases.
The target triple is now stored in the `BuildMetadata`.
If cargo is invoked the triple will be detected with the usual mechanism while
the `BuildMetadata` is generated.
During build-reuse the target triple is loaded from the `BuildMetadataSummary`.
If the target was not manually set, the host target-triple will be used
during serialization. This ensures correct behaviour in cases where
runner has a different default toolchain.
I have tested this locally with a docker container with cross compilation for windows and running with …
> fix: respect test runner during build reuse

- nextest-runner/src/cargo_config.rs
- nextest-runner/src/target_runner.rs
The main issue to note here is https://github.com/rust-lang/cargo/issues/10992.
> [nextest-runner] update Cargo config precedence to match upstream

- nextest-runner/src/runner.rs
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
> Optimization: Rm use of `BufReader` and lazily allocate space for `BytesMut` in `TestRunner::run_test_inner`

- .config/nextest.toml
- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- release.toml
> [nextest-runner] before terminating, replace last SLOW message with TERMINATING

- .config/nextest.toml
- Cargo.lock
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- nextest-metadata/Cargo.toml
- nextest-runner/Cargo.toml
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/platform.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/target_runner.rs
- workspace-hack/Cargo.toml
Use target-spec with the new target-spec-miette crate for producing errors.
> add support for restricting overrides to particular platforms

- Cargo.lock
- nextest-runner/Cargo.toml
- nextest-runner/src/helpers.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/signal.rs
- nextest-runner/src/time/mod.rs
- nextest-runner/src/time/pausable_sleep.rs
- nextest-runner/src/time/stopwatch.rs
Some interesting issues we've faced while developing this:
Sometimes nextest just hangs if Ctrl-Z comes in at the wrong time. This is due to a fundamental race in posix_spawn: https://sourceware.org/pipermail/libc-help/2022-August/006263.html
To solve this issue, we use a double-spawn approach (with `NEXTEST_EXPERIMENTAL_DOUBLE_SPAWN=1` set in the environment and with Rust beta, currently):
1. Block SIGTSTP before calling posix_spawn.
2. Rather than spawning the test process directly, spawn `cargo-nextest __double-spawn <test-binary and args>`.
3. In the child process, unblock SIGTSTP before execing the child process.
We need a way to pause all our timers when we're pausing, then resume them afterwards. To do this, introduce a `PausableTimer` with `pause()` and `resume()` methods.
> [WIP] [nextest-runner] add rudimentary support for handling SIGTSTP and SIGCONT

- .cargo/config.toml
- .config/hakari.toml
- .config/nextest.toml
- .github/workflows/ci.yml
- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- fixtures/nextest-tests/tests/basic.rs
- integration-tests/Cargo.toml
- nextest-metadata/Cargo.toml
- nextest-runner/Cargo.toml
- nextest-runner/src/console.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
- quick-junit/Cargo.toml
- scripts/cargo-release-publish.sh
- workspace-hack/Cargo.toml
On Windows, spawned processes can leave the Tokio runtime hanging.
Ensure that the runtime is shut down immediately rather than waiting for
it to exit -- it is better for nextest to leak resources than to hang.
Fixes https://github.com/nextest-rs/nextest/issues/656.
> [nextest-runner] shutdown Tokio runtime aggressively

- fixtures/nextest-tests/tests/basic.rs
This is now fixed in the released version of nextest.
> [fixtures] update sleep timeout to 360 seconds

- cargo-nextest/src/dispatch.rs
cargo llvm-cov started setting NEXTEST_TEST_THREADS=1, which breaks this
test.
> [cargo-nextest] remove all NEXTEST_ env vars from argument parsing test

- site/src/book/pre-built-binaries.md
This PR does exactly what the title suggests and updates the book/website about installing `nextest` on Arch Linux 🐻
> [site] add information about installing nextest on Arch Linux

- .config/nextest.toml
- Cargo.lock
- cargo-nextest/src/errors.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/config.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/runner.rs
Test groups allow for mutual exclusion or other concurrency limits among sets of tests. This is useful to emulate tests that must be run in a single-threaded fashion.
> [nextest-runner] add support for test groups

- .cargo/config.toml
- Cargo.lock
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/unicode_string.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/cargo_config/env.rs
- nextest-runner/src/config.rs
- nextest-runner/src/config/identifier.rs
- nextest-runner/src/double_spawn.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/reuse_build/archive_reporter.rs
See doc comment to `ConfigIdentifier` for more.
We'll eventually want to restrict profile names to these as well, but maybe some other day.
> [nextest-runner] restrict group names to valid identifiers

- nextest-runner/src/config.rs
This PR addresses #388:
- Introduces `NextestConfigImpl::DEFAULT_PROFILES`, a const containing all the nextest defined profiles (at the moment this only includes `default` and `default-miri`)
- Looks through all profiles in a project's config for profiles with the `default-` prefix that are not in `NextestConfigImpl::DEFAULT_PROFILES` and produces a warning for each of them
Note that I ended up doing this in `nextest-runner/src/config.rs` instead of in `cargo-nextest` since AFAICT this is where a lot of the early validation of config files is being done and similar warnings were already being emitted there. Happy to move if you still feel the binary (e.g. somewhere in `nextest-runner/src/dispatch.rs`?) is a better place for this.
- Ran `cargo xfmt`
- Ran `cargo nextest run …
> Add a warning for unknown default profiles

- site/src/book/pre-built-binaries.md
- Update install-action to v2 (Only docs need to be updated since the `@<tool_name>` shorthand is used in `.github/workflows`.)
- Fix docs on specifying version in install-action. The current docs mentions `version: ` input option, but such an option has never been supported by install-action, and the correct syntax is the `<tool_name>@<version>` syntax in the `tool:` input option.)
> Update install-action to v2 and fix docs

- .github/workflows/release.yml
This fixes release workflow failure: https://github.com/nextest-rs/nextest/actions/runs/3908669436/jobs/6679052947
> Fix release workflow failure

- cargo-nextest/src/dispatch.rs
- fixtures/nextest-tests/.config/nextest.toml
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-3.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-4.snap
- nextest-filtering/examples/parser.rs
- nextest-filtering/src/bin/generate-expr-corpus.rs
- nextest-filtering/src/compile.rs
- nextest-filtering/src/expression.rs
- nextest-filtering/src/lib.rs
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/proptest_helpers.rs
- nextest-filtering/tests/match.rs
- nextest-runner/src/config/overrides.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/show_config/test_groups.rs
- nextest-runner/tests/integration/basic.rs
No reason for filters to be restricted to one line.
Also make `show-config` provide a cleaner representation of the string. This was a bit of a rabbit hole (required adding some fidelity to `ParsedExpr`) but not too bad overall.
Closes #868.
> [nextest-filtering] handle multiline filter strings

- Cargo.lock
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- fixtures/custom-target/my-target.json
- nextest-filtering/Cargo.toml
- nextest-metadata/Cargo.toml
- nextest-runner/Cargo.toml
- nextest-runner/src/cargo_config/discovery.rs
- nextest-runner/src/cargo_config/env.rs
- nextest-runner/src/cargo_config/target_triple.rs
- nextest-runner/src/cargo_config/test_helpers.rs
- nextest-runner/src/config/test_helpers.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/target_runner.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
- nextest-runner/tests/integration/target_triple.rs
- workspace-hack/Cargo.toml
Pull in target-spec version 2, which implements support for custom targets.
Note that custom targets are not supported in `platform` overrides, just in `--target`/`CARGO_BUILD_TARGET`/`build.target`.
> [nextest-runner] add support for custom targets

- quick-junit/src/report.rs
- quick-junit/src/serialize.rs
- quick-junit/tests/fixture_tests.rs
- quick-junit/tests/fixtures/basic_report.xml
Fixes #897
Simple change adding support for test case properties. These properties are used by some systems for metadata like attachments, links, and test steps, so are useful to be able to set.
> [quick-junit] Add support for test case properties

- cargo-nextest/src/cargo_cli.rs
Change:
- Add `--cargo-quiet` flag to `nextest run` to suppress standard build output. Warnings and errors are still printed.
This makes it possible to run it with less noise. LMK if anything is missing.
Does this file need to be updated? Dont know how that is used https://github.com/ggwpez/nextest/blob/71ebdf65fbe24a64382524ae01e1ab57804f111e/site/help-text/list-help.txt#L31
> Add flag `--cargo-quiet`

- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/time/stopwatch.rs
- nextest-runner/tests/integration/fixtures.rs
All test events now also carry a total time elapsed. This will be useful for DTrace support if/when we get to it.
> [nextest-runner] wrap test events in TestEventKind

- site/src/book/how-it-works.md
addresses https://github.com/nextest-rs/nextest/issues/942
> added section to how-it-works on contributing back to cargo

- nextest-runner/src/list/test_list.rs
- nextest-runner/src/test_command.rs
We're going to use these parts in setup scripts.
> [nextest-runner] factor out parts of test command creation

- nextest-runner/src/cargo_config/discovery.rs
- nextest-runner/src/config/nextest_version.rs
- nextest-runner/src/config/scripts.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/update.rs
Consists of a few clippy warnings, and also the ability to parse the new test panic messages produced by Rust 1.73.
> [meta] updates for Rust 1.73

- nextest-runner/src/runner.rs
Implementation for #931
Removes `slow-timeout.grace-period` and replaces it with `shutdown-grace-period` at the top-level config. The new config value applies to all shutdown events.
> generalize slow-timeout.grace-period to all shutdown events

- Cargo.lock
- quick-junit/Cargo.toml
- quick-junit/src/report.rs
- quick-junit/tests/fixtures/basic_report.xml
Previously the escape character itself was removed, but the rest of the escape sequence was left in place, resulting in useless and seemingly random characters in the output. (Unless some tools expect this and know how to handle it, but that isn't the case for the tools I use.)
There was already a test that asserted this. I assumed the goal of that test was just to validate that illegal characters (like the escape character) didn't make it into the output, and I've adjusted it to verify that the entire sequence is stripped out.
> Strip ANSI escapes from JUnit output

- Cargo.lock
- quick-junit/Cargo.toml
- workspace-hack/Cargo.toml
Hey, we are using quick-junit in Deno. I'm trying to get rid of dynamic library that cost startup time. It turns out `chrono`'s "clock" features pulls in `iana-time-zone` which pulls in the `core-foundation` on macOS. 
This PR just disables the default features (including "clock") in chrono, no functional changes.
> Use bare minimum chrono features

- nextest-filtering/src/errors.rs
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/unicode_string.rs
Previously we'd report something like
```
error: expected close parenthesis
╭────
1 │ package(nexte\$)
·              ▲
·              ╰── missing `)`
╰────
error: expected end of expression
╭────
1 │ package(nexte\$)
·              ─┬─
·               ╰── unparsed input
╰────
```
Now, we report:
```
error: invalid escape character
╭────
1 │ package(nexte\$)
·              ─┬
·               ╰── invalid escape character
╰────
```
> [nextest-filtering] better error reporting for invalid escapes

- fixtures/nextest-tests/Cargo.lock
- fixtures/nextest-tests/Cargo.toml
- fixtures/nextest-tests/cdylib/cdylib-link/build.rs
- fixtures/nextest-tests/cdylib/cdylib-link/src/lib.rs
- fixtures/nextest-tests/tests/basic.rs
- fixtures/nextest-tests/with-build-script/Cargo.toml
- fixtures/nextest-tests/with-build-script/build.rs
- fixtures/nextest-tests/with-build-script/src/lib.rs
- integration-tests/tests/integration/fixtures.rs
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-2.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-4.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-6.snap
- nextest-metadata/src/test_list.rs
- nextest-runner/src/config/scripts.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/reuse_build/archive_reporter.rs
- nextest-runner/src/reuse_build/archiver.rs
- nextest-runner/src/reuse_build/unarchiver.rs
- nextest-runner/src/test_command.rs
- nextest-runner/tests/integration/fixtures.rs
- site/src/CHANGELOG.md
- Set `OUT_DIR`, similar to what Cargo does.
- Archive build script output dirs to one level for workspace packages. We may have to add configuration to allow more to be nested in the future, but this should start off as being conservative.
Closes #1140.
> [nextest-runner] also expose build script output dirs

- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/reporter/structured.rs
- nextest-runner/src/reporter/structured/libtest.rs
There are a couple of todos, but the biggest missing piece is combined stdout/err output.
Opening this as a draft while I make the combined output helper.
> Add libtest json output option

- nextest-runner/default-config.toml
Did I understand wrong that after a retry if the test succeeds is marked as flakey?
If so, should the text in the default-config.toml be as suggested by this PR?
> Fix default-config.toml comment on `retry` semantics

- nextest-filtering/src/errors.rs
- nextest-filtering/src/parsing.rs
We only support a single `|` and `&` in this position.
> [nextest-filtering] catch || and && as error cases

- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/unicode_string.rs
Incomplete specifically means that there isn't enough data to continue processing.
Its a bit of a hack to reuse this for error recovery. This will no longer work if/when moving to `winnow`.
At least judging by the tests, nothing fails when removing this so its good enough?
> [nextest-filering] Remove reliance on Incomplete

- Cargo.lock
- nextest-runner/Cargo.toml
- nextest-runner/src/list/output_format.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/test_filter.rs
- workspace-hack/Cargo.toml
> [nextest-runner] print outputs after SIGTERM or SIGHUP

- nextest-runner/src/errors.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
In debugging <https://github.com/sourcefrog/cargo-mutants/issues/226> I found that invocations like `~/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/bin/cargo nextest run` cause some test failures in the nextest tree, for reasons I'm still working to understand. 
In `main`, those errors are printed like this, with a pile of ASCII byte values:
```
thread 'basic::test_termination' panicked at nextest-runner/tests/integration/fixtures.rs:383:10:
test list successfully created: CommandFail { binary_id: RustBinaryId("cdylib-example"), command: ["/home/mbp/src/nextest/fixtures/nextest-tests/target/debug/deps/cdylib_example-9222c584dde9dbd0", "--list", "--format", "terse"], exit_status: ExitStatus(unix_wait_status(32512)), stdout: [], stderr: [47, 104, 111, 109, 101, 47, 109, 98, 112, 47, …
```
> Make errors from `make_test_list` legible

- Cargo.lock
- nextest-filtering/Cargo.toml
- nextest-filtering/src/errors.rs
- nextest-filtering/src/expression.rs
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/glob.rs
- nextest-filtering/src/parsing/unicode_string.rs
- workspace-hack/Cargo.toml
@sunshowers expressed interest in `winnow` and I figured porting an existing project they were familiar with would make it easier when they try it out.
When i first switched from `nom`s pure `Fn(I) -> (I, O)` parser model to `Fn(&mut I) -> O`, I was concerned about it making things worse.  It does have the downside of requiring more lifetime annotations to disambiguate things but I feel like it has been proven time and again to simplify code.  In this case, it removed a lot of bookkeeping from the functions, making the intentional bookkeeping more obvious, and it allowed the removal of `RefCell` for error recovery.
I broke this up into a lot of commits
- Smaller nuggets to review
- Easier to call out the differences
- Easier for me to deal with merge conflicts.
I did put a little too much …
> [nextest-filtering] Replace `nom` parser with `winnow`

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- cargo-nextest/Cargo.toml
- fixtures/nextest-tests/Cargo.toml
- nextest-filtering/CHANGELOG.md
- nextest-filtering/Cargo.toml
- nextest-metadata/CHANGELOG.md
- nextest-metadata/Cargo.toml
- nextest-metadata/README.md
- nextest-metadata/src/lib.rs
- nextest-runner/Cargo.toml
- quick-junit/CHANGELOG.md
- quick-junit/Cargo.toml
- quick-junit/README.md
- quick-junit/src/lib.rs
- site/src/book/installing-from-source.md
Some dependencies are starting to require newer versions of Rust, and this matches our stability guarantee.
> [meta] bump MSRV to Rust 1.73

- .github/workflows/ci.yml
- .github/workflows/release.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> [ci] use M1 runners for macOS builds

- Cargo.lock
- nextest-filtering/Cargo.toml
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/unicode_string.rs
This resolves a couple of deprecations.  I'm thinking of doing 0.6 soon and I expect this to be the end of the deprecations that will happen in the lead up.  So for people on 0.5.36 with all deprecations resolved, i expect it to be a trivial version bump to 0.6 for most people.
> Update to Winnow 0.5.36

- nextest-runner/default-config.toml
I think this is all that's needed? Quite a slick system if so.
Closes https://github.com/nextest-rs/nextest/issues/1346
> Have Miri use all the cores by default

- cargo-nextest/src/dispatch.rs
- integration-tests/tests/integration/main.rs
- nextest-runner/default-config.toml
- nextest-runner/src/config/archive_include.rs
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/mod.rs
- nextest-runner/src/reuse_build/archiver.rs
Progress towards https://github.com/nextest-rs/nextest/issues/1340
This PR implements the design given by rain in https://github.com/nextest-rs/nextest/issues/1340#issuecomment-1972163611
However it only implements the smallest possible functionality that will the allow the full design to be implemented in a backwards compatible manner in the future.
This is because I would like to land a small part of the design to ensure I am on track and also because I cant afford the time to implement all of these features right now.
The full implementation will look like:
```toml
[profile.ci]
archive-include = [
{ path = "foo", relative-to = "target" },
{ path = "bar/*", relative-to = "target-profile" },
]
```
However this PR's config will only support:
```toml
[profile.ci]
archive-include = [
{ path …
```
> Add archive-include config

- site/src/book/benchmarks.md
The link works in GitHub but is broken on the deployed website.
> Fix link to "other features" from benchmarks.md

- .github/workflows/ci.yml
This version should include bcryptprimitives.dll, which is required by newer versions of Rust.
> [ci] update wine version for target runner test

- .github/workflows/ci.yml
- Cargo.lock
- cargo-nextest/src/reuse_build.rs
- fixtures/nextest-tests/tests/basic.rs
- integration-tests/tests/integration/snapshots/integration__archive_includes.snap
- integration-tests/tests/integration/snapshots/integration__archive_includes_without_uds.snap
- integration-tests/tests/integration/snapshots/integration__archive_missing_includes.snap
- integration-tests/tests/integration/snapshots/integration__archive_no_includes.snap
- nextest-metadata/src/test_list.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/list/rust_build_meta.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/platform.rs
- nextest-runner/src/reuse_build/archive_reporter.rs
- nextest-runner/src/reuse_build/archiver.rs
- nextest-runner/src/reuse_build/mod.rs
- nextest-runner/src/reuse_build/unarchiver.rs
- scripts/nextest-without-rustup.sh
- site/src/book/env-vars.md
- workspace-hack/Cargo.toml
We need stdlibs in two cases:
1. For proc-macro tests, the host stdlib.
2. For -C prefer-dynamic, the target stdlib.
Archive and reuse them, if available.
Also add tests for running nextest without rustup, including archives. This
should be a pretty comprehensive test.
> [nextest-runner] archive and reuse stdlibs

- .github/workflows/ci.yml
- nextest-runner/src/cargo_config/discovery.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/runner.rs
`cargo clippy --all-features --all-targets` will result the following warnings on windows. This PR:
* fixes those warnings
* runs the lint CI on Windows as well
* fail the CI if clippy results in any warnings
```
PS C:\Users\XXXXXXXX\src\nextest> cargo clippy --all-features --all-targets
Checking nextest-runner v0.56.1 (C:\Users\XXXXXXXX\src\nextest\nextest-runner)
warning: the `Err`-variant returned from this function is very large
--> nextest-runner\src\cargo_config\discovery.rs:58:10
|
58   |       ) -> Result<Self, CargoConfigError> {
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
::: nextest-runner\src\errors.rs:1163:5
|
1163 | /     ConfigParseError {
1164 | |         /// The path of the config file
1165 | |         path: Utf8PathBuf,
1166 | |
...    |
1169 | |         error: …
```
> Fix clippy error on Windows

- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- integration-tests/tests/integration/main.rs
- nextest-metadata/src/exit_codes.rs
- nextest-runner/src/reporter.rs
- nextest-runner/src/runner.rs
Default to `warn` currently, but can also be `fail` or `pass`. The plan is to default to `fail` in the future (see #1646).
> [cargo-nextest] add a new --no-tests option

- Cargo.lock
- Cargo.toml
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/helpers.rs
- nextest-runner/src/reporter/mod.rs
- nextest-runner/src/reporter/structured.rs
- nextest-runner/src/reporter/structured/libtest.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/test_output.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
With very long outputs, it can often be hard to tell which parts correspond immediately to the failure. Highlight those parts so users can easily tell.
> highlight interesting parts of the output

- cargo-nextest/src/dispatch.rs
- fixture-data/src/models.rs
- fixture-data/src/nextest_tests.rs
- integration-tests/tests/integration/fixtures.rs
- integration-tests/tests/integration/main.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/test_filter.rs
- nextest-runner/tests/integration/basic.rs
My half-finished attempt at #1483. It works, but clearly is not acceptable as-is because it adds a `todo!()` to one test, and doesn't add any tests for the new behavior.
Any hints as to how to get this into a mergable shape would be appreciated.
> WIP: Add support for --skip and --exact test binary arguments

- cargo-nextest/src/dispatch.rs
- integration-tests/tests/integration/main.rs
`--exact` is actually a global option, not one that takes a pattern as an argument.
> [cargo-nextest] fix --exact semantics

- cargo-nextest/src/dispatch.rs
- integration-tests/tests/integration/main.rs
- nextest-runner/src/test_filter.rs
If both `--skip` and `--exact` are passed in at the same time, then `--skip` also matches filters exactly.
> [cargo-nextest] also fix --skip with --exact

- .github/workflows/ci.yml
The Wine PPA for Ubuntu 22.04 seems to currently be broken, returning a `Packages.xz` that doesn't match the `InRelease` manifest. Try out Ubuntu 24.04 and the shipped version of Wine.
> [ci] try using Ubuntu 24.04

- fixture-data/src/nextest_tests.rs
- fixtures/nextest-tests/with-build-script/build.rs
- fixtures/nextest-tests/with-build-script/src/lib.rs
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_basic.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_bound_all.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_all.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_default.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-2.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-4.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-6.snap
- nextest-runner/src/reuse_build/archiver.rs
- nextest-runner/src/test_command.rs
- site/src/docs/configuration/env-vars.md
As discussed in #1787, `cargo test` does this, so `nextest` should too.
I added warnings in case the build script output file is not found, this should usually have been created when cargo executes the build script.
I also decided to package the build script output _file_ in the same step as the build script output _directory_.
Let me know if you prefer creating a separate step for this.
I tried to approach this with minimal changes, maybe it would be nicer to store the path to the `$OUT_DIR` _parent_, so that getting the path of the output file is a tad simpler, but that would have required me touching more code.
Let me know if you have suggestions for implementing any of this differently.
Side note: trying to run tests with `cargo run -p cargo-nextest -- nextest run --all-features` …
> Set environment variables specified via `cargo::rustc-env` in the build script

- cargo-nextest/src/dispatch.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/runner.rs
Trying to handle reporter errors in the main runner loop is a bit of a mess. Instead, handle them at a higher level and use a oneshot channel to indicate that an error has occurred. This fits in quite naturally with the rest of the event-driven system.
Also change "canceled" to "cancelled" for consistency.
> [nextest-runner] simplify reporter error handling

- nextest-runner/src/errors.rs
- nextest-runner/src/reporter/structured.rs
- nextest-runner/src/reporter/structured/libtest.rs
All errors go in this central location.
> [nextest-runner] move FormatVersionError to errors.rs

- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
cargo --jobs supports negative values: https://github.com/rust-lang/cargo/issues/9217
currently this fails:
```
cargo nextest run --build-jobs -1                                                                                                                                                                                                   
error: unexpected argument '-1' found
tip: to pass '-1' as a value, use '-- -1'
```
because clap doesn't support this by default and requires `allow_hyphen_values = true`
https://github.com/clap-rs/clap/issues/1245
> feat: support hyphen values for --build-jobs

- cargo-nextest/src/dispatch.rs
- integration-tests/tests/integration/main.rs
Per https://github.com/nextest-rs/nextest/discussions/1646.
> [cargo-nextest] change no-tests behavior

- fixture-data/src/models.rs
- fixture-data/src/nextest_tests.rs
- fixtures/nextest-tests/tests/basic.rs
- integration-tests/tests/integration/fixtures.rs
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_basic.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_bound_all.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_all.snap
- integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_default.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-2.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-4.snap
- integration-tests/tests/integration/snapshots/integration__show_config_test_groups-6.snap
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
Per #1891 -- this bug was quietly fixed but there was no coverage for it apparently.
> Add a FAIL + LEAK test along with coverage for outputs being displayed

- nextest-runner/src/runner.rs
These enums only have one variant at the moment -- more will be added in the future.
> Add a couple of wrapper enums

- .github/workflows/ci.yml
- Cargo.toml
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- integration-tests/tests/integration/fixtures.rs
- integration-tests/tests/integration/temp_project.rs
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/proptest_helpers.rs
- nextest-filtering/tests/match.rs
- nextest-runner/src/cargo_config/env.rs
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/overrides.rs
- nextest-runner/src/double_spawn.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/indenter.rs
- nextest-runner/src/list/output_format.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reuse_build/archiver.rs
- nextest-runner/src/runner.rs
- nextest-runner/src/test_command/unix.rs
- nextest-runner/src/test_filter.rs
- nextest-runner/src/time/mod.rs
- nextest-runner/src/time/stopwatch.rs
- nextest-runner/src/update.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
This caught a few outdated lints and a few that should have been `cfg(test)`.
> [meta] update MSRV to Rust 1.81, switch lints from allow to expect

- nextest-runner/src/reporter/displayer.rs
Previously, our headers would always insert a leading newline to compensate for situations where the output didn't have a trailing newline in it. This isn't quite right (what if the last output doesn't have a newline in it)? It also causes issues with situations where RESET_COLOR needs to be inserted immediately before the last newline.
Change our code to always insert a trailing newline, and the trailer immediately before that.
> [nextest-runner] handle outputs with/without trailing newlines better

- Cargo.lock
- integration-tests/tests/integration/fixtures.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/reporter/displayer.rs
Nextest has rigorously followed Cargo's theming so far -- but I think it's time to start breaking from that a bit. An easy change is to use Unicode hbar and progress characters.
> [nextest-runner] use Unicode characters if available

- nextest-runner/src/config/scripts.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/structured/libtest.rs
- nextest-runner/src/reporter/structured/snapshots/nextest_runner__reporter__structured__libtest__test__strips_human_output_start_error.snap
- nextest-runner/src/runner.rs
- nextest-runner/src/test_command.rs
- nextest-runner/src/test_command/imp.rs
- nextest-runner/src/test_output.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
* Don't eat up stdout/stderr if there's an error that occurs after the process is spawned
* Scripts can now combine stdout and stderr (though this isn't exposed in the UI yet).
* Fix up names to reflect that "child" can mean either a test process or a script process.
This is going to need a bunch of TLC, but I think this is generally a good shape for the types to be in.
> [nextest-runner] improve error handling for child process management

- nextest-runner/src/reporter/displayer.rs
Using `TestInstanceId` makes this code somewhat easier to test.
> [nextest-runner] use TestInstanceId in more spots

- .config/nextest.toml
- nextest-runner/src/runner.rs
Make delay timers obey these signals.
> [nextest-runner] make delays obey SIGTSTP and SIGCONT

- nextest-runner/src/errors.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/reporter/aggregator.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__info_response_output.snap
- nextest-runner/src/runner.rs
- nextest-runner/src/signal.rs
- nextest-runner/src/test_command/imp.rs
- nextest-runner/src/test_output.rs
- nextest-runner/src/time/pausable_sleep.rs
- nextest-runner/src/time/stopwatch.rs
Part 1 of work to perform interactive queries.
With this change, if nextest receives either SIGINFO (where available) or SIGUSR1, it will print a list of all currently running tests with their states. The full test state machine is modeled in the event responses, along with possible sources of errors.
I tried making Ctrl-Break on Windows do the same thing, but unfortunately that doesn't quite work in practice. That's because Ctrl-Break is received by all processes connected to the console, not just by the equivalent of the "foreground process group". The printing out of info works, but running tests are immediately aborted as well. So remove this. (In interactive terminals we'll support an alternative -- pressing `i` -- which should work for most use cases on Windows.)
There is also an …
> [nextest-runner] handle SIGINFO and SIGUSR1 to dump info to screen

- Cargo.lock
- Cargo.toml
- cargo-nextest/src/dispatch.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/input.rs
- nextest-runner/src/lib.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/runner.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/target_runner.rs
- workspace-hack/Cargo.toml
In prior work (#1938) we enabled the `SIGUSR1` and `SIGINFO` handlers to dump internal state to standard output.
However, those handlers aren't present on all platforms.
* `SIGINFO` doesn't exist on Linux. `SIGUSR1` exists but is hard to send signals over (have to use `kill`, nothing like `^T`).
* Windows' very basic signal handling mechanism isn't really up to the task.
As an alternative, allow these platforms to specify `t` to dump current test information to the interactive terminal.
It would also be interesting to support a Unix domain socket as a way to query current state in the future, and have a separate instance of nextest be able to connect to the socket -- this work naturally builds towards that kind of model.
> [nextest-runner] support pressing `t` to dump current test info

- .config/nextest.toml
- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/tests/custom-harness.rs
- nextest-runner/default-config.toml
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/mod.rs
- nextest-runner/src/config/overrides.rs
- nextest-runner/src/config/phase.rs
- nextest-runner/src/config/retry_policy.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/runner/executor.rs
Add a way to do this:
```toml
[[profile.default.overrides]]
filter = "test(some_filter)"
phase.run.extra-args = ["--test-threads", "1"]
```
See https://github.com/nextest-rs/nextest/discussions/1959 for why this is required. This is an advanced option that should be used with care, but it's worth implementing.
The `phase.run` is because (a) we may want `phase.list` in the future as well, and (b) in the future, we'll want to support setting the environment here as well.
> [nextest-runner] add a way to pass extra args at runtime

- nextest-runner/src/reporter/aggregator/junit.rs
Test suites that run first are now stored first in the JUnit output. Previously this was effectively in completely random order, which doesn't seem right.
> [nextest-runner] use an IndexMap for JUnit aggregation

- nextest-runner/src/config/archive.rs
- nextest-runner/src/config/scripts.rs
- nextest-runner/src/list/binary_list.rs
- nextest-runner/src/reporter/error_description.rs
- nextest-runner/src/reporter/structured/libtest.rs
> refactor: remove raw `#`s that are unnecessary

- nextest-runner/src/helpers.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/error_description.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__windows_tests__ctrl_c_code.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__windows_tests__stack_violation_code.snap
- nextest-runner/src/runner/dispatcher.rs
- nextest-runner/src/runner/executor.rs
- nextest-runner/src/runner/internal_events.rs
- nextest-runner/src/runner/windows.rs
- site/src/docs/design/architecture/signal-handling.md
Previously on Windows, we would not do anything at all on receiving Ctrl-C, letting tests exit on their own.
With this change, in case of Ctrl-C, nextest will apply the same grace period that it does on Unix. By default, nextest will now wait 10 seconds before calling `TerminateJobObject` on the test. Like on Unix, a double Ctrl-C will kill the test immediately.
The behavior in case of timeouts is unchanged -- call `TerminateJobObject` immediately.
This PR also has a few more fixes to Windows display, and to cancellation on all platforms.
> [nextest-runner] use grace period on receiving Windows Ctrl-C

- nextest-runner/src/runner/dispatcher.rs
- nextest-runner/src/runner/executor.rs
- nextest-runner/src/runner/imp.rs
- nextest-runner/src/runner/internal_events.rs
- nextest-runner/src/runner/unix.rs
- nextest-runner/src/runner/windows.rs
The request channel with the dispatcher provides a principled way to do cancellation-related cleanup.
> cancellation-related cleanup

- nextest-runner/src/errors.rs
- nextest-runner/src/helpers.rs
- nextest-runner/src/reporter/aggregator/junit.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/error_description.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__windows_tests__ctrl_c_code.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__windows_tests__job_object.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__windows_tests__stack_violation_code.snap
- nextest-runner/src/runner/executor.rs
- nextest-runner/src/runner/internal_events.rs
- nextest-runner/src/runner/unix.rs
- nextest-runner/src/runner/windows.rs
In case of a Ctrl-C grace period expiring, we should make it clear to users what's happening rather than just printing out "FAIL".
> [nextest-runner] make Windows job object termination clearer

- .github/workflows/coverage.yml
There's a bunch of Windows-specific code that is covered, but isn't reflected in the coverage metrics.
> [ci] run coverage on Windows as well

- Cargo.lock
- Cargo.toml
- cargo-nextest/src/cargo_cli.rs
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
- integration-tests/Cargo.toml
- integration-tests/tests/datatest/custom_target.rs
- integration-tests/tests/datatest/helpers.rs
- integration-tests/tests/datatest/main.rs
- integration-tests/tests/datatest/snapshots/custom-invalid/invalid-arch.json-stderr.snap
- integration-tests/tests/datatest/snapshots/custom-invalid/invalid-endian.json-stderr.snap
- integration-tests/tests/datatest/snapshots/custom-invalid/invalid-family.json-stderr.snap
- integration-tests/tests/datatest/snapshots/custom-invalid/invalid-target-pointer-width.json-stderr.snap
- integration-tests/tests/datatest/snapshots/custom-invalid/missing-arch.json-stderr.snap
- integration-tests/tests/datatest/snapshots/custom-invalid/syntax-error.json-stderr.snap
- nextest-runner/src/errors.rs
- workspace-hack/Cargo.toml
Currently, if nextest cannot parse a target triple it prints a warning, and instead just builds on the host platform. I think that isn't the right behavior, and instead nextest should loudly fail.
Implement this change: fail with a clear error message. I consider the current behavior a bug, so I don't think this needs to go through the behavior change process.
Also, hook up miette support to produce better error messages if deserializing custom JSON fails, and add tests to verify this behavior.
For target runners, we continue to warn rather than fail.
> [cargo-nextest] fail if --target wasn't understood

- nextest-runner/src/input.rs
- nextest-runner/src/reporter/aggregator/junit.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/runner/dispatcher.rs
If input handling is enabled, also handle newline/enter events.
* If a progress bar is present, take a snapshot of it.
* If not, then print a blank line.
This allows for the common usage pattern of users pressing enter-enter-enter to
mark a particular point in the output.
> handle newline/enter in input events

- nextest-runner/src/reporter/aggregator/junit.rs
- nextest-runner/src/reporter/displayer.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_exec_failed_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_exec_failed_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_failed_one_passed_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_failed_one_passed_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_failed_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_failed_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_exec_failed_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_exec_failed_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_failed_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_failed_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_timed_out_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_setup_script_timed_out_without_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_timed_out_with_cancel_reason.snap
- nextest-runner/src/reporter/snapshots/nextest_runner__reporter__displayer__tests__one_timed_out_without_cancel_reason.snap
- nextest-runner/src/runner/dispatcher.rs
- site/src/docs/design/architecture/input-handling.md
- site/src/outputs/enter-output.ansi
Rather than trying to do different things with and without the progress bar, just display a summary of the current state (everything that would be shown except for the progress itself).
Also add some tests.
> [nextest-runner] better InputEnter display

- nextest-runner/src/reporter/displayer/imp.rs
- nextest-runner/src/reporter/displayer/snapshots/nextest_runner__reporter__displayer__imp__tests__final_status_output.snap
Accidentally switched a `writeln!` to a `write!` in 6f9689329e9cda1f96f3ed37443df50e3a450501. Whoops, this bit of code didn't quite have coverage, so added some tests.
> [nextest-runner] fix accidentally-missing newline in write_final_status

- nextest-runner/src/reporter/displayer/progress.rs
On continuing, ensure that the elapsed time is set to the actual time.
> [nextest-runner] reset progress bar elapsed time on SIGCONT

- Cargo.lock
- Cargo.toml
- nextest-filtering/src/parsing.rs
- nextest-filtering/src/parsing/glob.rs
With 0.7, `ErrMode` is optional.  It looks like `cut_err` isn't used but I held off on migrating from `ModalResult` to `winnow::Result` and `ModalParser` to `Parser` in case there is a future possibility of using `ErrMode`.
> chore: Upgrade to Winnow 0.7

- integration-tests/tests/integration/fixtures.rs
- nextest-runner/tests/integration/basic.rs
- nextest-runner/tests/integration/fixtures.rs
- nextest-runner/tests/integration/target_runner.rs
Newer versions of Rust seem to return SIGABRT, not SIGSEGV. This is all right.
> fix tests on newer Rust nightlies

- Cargo.lock
- Cargo.toml
- cargo-nextest/Cargo.toml
- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/version.rs
- fixture-data/Cargo.toml
- fixture-data/src/nextest_tests.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/list/test_list.rs
- nextest-runner/src/redact.rs
- nextest-runner/src/reporter/error_description.rs
- nextest-runner/src/test_command.rs
- nextest-runner/src/test_command/windows.rs
- nextest-runner/tests/integration/fixtures.rs
`Lazy` is now in Rust 1.80+ as `LazyLock`, so switch to that.
> [meta] remove direct dep on once_cell

- cargo-nextest/src/dispatch.rs
- integration-tests/tests/integration/main.rs
This was previously done to avoid confusion between test name filters and arguments. But we believe the new `--no-tests` default to fail sufficiently mitigates the downside, and uniformity across options is valuable.
Closes #1933.
> [cargo-nextest] don't require equals for `--max-fail` and `--no-tests`

- .config/nextest.toml
- integration-tests/src/env.rs
This is set with nextest 0.9.89 and above.
> [integration-tests] ensure NEXTEST_PROFILE is always set

- cargo-nextest/src/dispatch.rs
- cargo-nextest/src/errors.rs
Sometimes, `cargo` doesn't produce any output whatsoever (e.g. #2246). Always show something to indicate what command's at fault.
> [cargo-nextest] produce our own output if `cargo metadata` fails

- nextest-runner/src/test_command/unix.rs
Previously, for combined output, we were using the same file descriptor and storing it three times:
1. In `.stdout`
2. In `.stderr`
3. In `state.theirs`.
`Stdio` consumes ownership of the fd, so this effectively meant that three `OwnedFd` instances were present, and fds would be dropped three times.
Now in a single-threaded program this is relatively harmless -- Rust just gets `EBADF` for the latter two calls. But in multithreaded programs this was completely broken, with a bit of a horrific race condition on Linux. Since Tokio uses pidfds for process event handling on Linux, this caused missed wakeups in this scenario:
1. Let's say we allocated fd 20 as the `theirs` end provided to the child process `Stdio`.
2. In thread 1, we dropped the child, closing fd 20 the first time.
3. In thread …
> [nextest-runner] correctly dup the fd with combined output

- Cargo.lock
- Cargo.toml
- cargo-nextest/src/dispatch.rs
- nextest-runner/src/reporter/displayer/imp.rs
- nextest-runner/src/reporter/imp.rs
- workspace-hack/Cargo.toml
Some use cases for this include copy/pasting output without block selection, and simple personal preference.
Also enable markdown parsing in clap help messages so bold text can be used.
> [cargo-nextest] add an option to disable indentation of output

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/tests/datatest/custom_target.rs
- nextest-runner/Cargo.toml
- nextest-runner/src/config/archive.rs
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/leak_timeout.rs
- nextest-runner/src/config/max_fail.rs
- nextest-runner/src/config/overrides.rs
- nextest-runner/src/config/retry_policy.rs
- nextest-runner/src/config/scripts.rs
- nextest-runner/src/config/slow_timeout.rs
- nextest-runner/src/config/test_group.rs
- nextest-runner/src/config/test_helpers.rs
- nextest-runner/src/config/test_threads.rs
- nextest-runner/src/config/threads_required.rs
- nextest-runner/src/config/tool_config.rs
Simplifies some tests a bit, and is also a good way to dogfood camino-tempfile-ext.
> [meta] use camino-tempfile-ext in tests

- fixtures/nextest-tests/.config/nextest.toml
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/overrides.rs
- nextest-runner/src/config/scripts.rs
- nextest-runner/src/errors.rs
- nextest-runner/src/runner/dispatcher.rs
- nextest-runner/src/runner/executor.rs
- nextest-runner/src/runner/internal_events.rs
Much of this has been adapted from #2018, with attention paid towards short-term back compat ("scripts.setup" instead of "script.setup").
> move setup scripts to be nested inside `scripts`

- site/src/docs/installation/from-source.md
v1 and v2 of [baptiste0928/cargo-install](https://github.com/baptiste0928/cargo-install) use a [deprecated cache API](https://github.com/baptiste0928/cargo-install/issues/32#issuecomment-2979676159).
> [site] update CI action `baptiste0928/cargo-install`: v1 -> v3

- cargo-nextest/src/dispatch.rs
- nextest-runner/default-config.toml
- nextest-runner/src/config/config_impl.rs
- nextest-runner/src/config/global_timeout.rs
- nextest-runner/src/config/mod.rs
- nextest-runner/src/config/slow_timeout.rs
- nextest-runner/src/reporter/displayer/progress.rs
- nextest-runner/src/reporter/events.rs
- nextest-runner/src/runner/dispatcher.rs
- nextest-runner/src/runner/imp.rs
- nextest-runner/src/time/pausable_sleep.rs
The global-timeout option gives an upper bound to how long a test run can last. When this limit is reached, the run is cancelled (similar to sending a signal to the process) and the results we got so far are displayed.
This is an implementation of the feature discussed in https://github.com/nextest-rs/nextest/discussions/1898.
> Add global-timeout option

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- workspace-hack/Cargo.toml
Should address https://github.com/nextest-rs/nextest/issues/2407.
> [meta] update MSRV to Rust 1.86 + dep updates

- nextest-runner/src/reporter/error_description.rs
- nextest-runner/src/reporter/structured/libtest.rs
Given that it is possible to distinguish between different suites in the structured reporter through the `nextest` property, this patch outputs test results as soon as they happen, when using `--reporter libtest-json-plus`.
`--reporter libtest-json` output is unaffected.
Maybe fixes #1256 ?
> Make `--reporter libtest-json-plus` output test results immediately

- nextest-runner/src/runner/executor.rs
- nextest-runner/src/runner/unix.rs
- nextest-runner/src/runner/windows.rs
This is the minimalist fix for https://github.com/nextest-rs/nextest/issues/2620.
With this changes my use-case works.
I only added `JOB_OBJECT_LIMIT_BREAKAWAY_OK`. `JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK` is closely related, I didn't need it but was wondering if I should also add it in good measure.
> [nextest-runner] Add "breakaway OK" to Windows job object limits
