nextest-runner/src/helpers.rs
nextest-runner/src/reporter.rs
nextest-runner/src/test_list.rs

print module path in cyan instead of white.

feat: print module path in cyan

---

nextest-runner/src/test_list.rs

These lines are produced by the default Rust benchmark harness.
Fixes #46.

[nextest-runner] ignore test-list lines that end with ': benchmark'

---

Cargo.lock
cargo-nextest/Cargo.toml
cargo-nextest/README.md
cargo-nextest/src/lib.rs
nextest-runner/CHANGELOG.md
nextest-runner/Cargo.toml
site/src/CHANGELOG.md

[nextest] update nextest-runner and cargo-nextest versions

---

cargo-nextest/src/dispatch.rs
cargo-nextest/src/lib.rs
cargo-nextest/src/reuse_build.rs
cargo-nextest/src/tests_integration/fixtures.rs
cargo-nextest/src/tests_integration/mod.rs
nextest-metadata/src/test_list.rs
nextest-runner/src/runner.rs
nextest-runner/src/target_runner.rs
nextest-runner/src/test_list.rs
nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/target_runner.rs

Prepare to get a new version of cargo-nextest out.

lots of cleanups

---

site/src/SUMMARY.md
site/src/book/coverage.md

Signed-off-by: Alex Chi <iskyzh@gmail.com>
close https://github.com/nextest-rs/nextest/issues/56
PTAL, thanks! cc @sunshowers

docs: add coverage support

---

cargo-nextest/src/output.rs

Signed-off-by: Alex Chi <iskyzh@gmail.com>
fix https://github.com/nextest-rs/nextest/issues/123

chore: use CARGO env variables for output settings

---

Cargo.lock
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
cargo-nextest/src/output.rs
nextest-filtering/src/errors.rs
nextest-filtering/src/expression.rs
nextest-filtering/src/lib.rs
nextest-filtering/src/parsing.rs
site/src/book/filtering-expression.md

[nextest-filtering] cleanup

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/hakari.yml

A poll I ran indicated that people prefer their PRs to run against a
speculative merge:
https://twitter.com/sunshowers6/status/1517239867511435264

[ci] check out result of speculative merge in PRs

---

.github/workflows/ci.yml
cargo-nextest/Cargo.toml
cargo-nextest/src/cargo_cli.rs
cargo-nextest/src/dispatch.rs
cargo-nextest/src/reuse_build.rs
nextest-filtering/Cargo.toml
nextest-metadata/Cargo.toml
nextest-runner/Cargo.toml
nextest-runner/src/lib.rs
nextest-runner/src/list/rust_build_meta.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/reuse_build.rs
nextest-runner/tests/integration/fixtures.rs
quick-junit/Cargo.toml

Some cleanup work

---

cargo-nextest/src/tests_integration/mod.rs
cargo-nextest/src/tests_integration/temp_project.rs

#243 is failing on Windows so try and break this up.

fixes for integration tests

---

Cargo.lock
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs

Misc fixes to land before archive support.

Preparation for archive support

---

cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
cargo-nextest/src/reuse_build.rs
cargo-nextest/src/tests_integration/mod.rs
nextest-runner/src/errors.rs
nextest-runner/src/reuse_build/archiver.rs
nextest-runner/src/reuse_build/mod.rs
nextest-runner/src/reuse_build/unarchiver.rs

Use the filename to detect the archive format.

[nextest-runner] add extensibility for future archive formats

---

nextest-runner/src/list/test_list.rs
nextest-runner/src/reuse_build/archiver.rs
nextest-runner/test-helpers/passthrough.rs

[nextest-runner] some more changes

---

Cargo.lock
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
cargo-nextest/src/output.rs
nextest-metadata/src/exit_codes.rs
nextest-runner/Cargo.toml
nextest-runner/src/errors.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/target_runner.rs
nextest-runner/src/update.rs

This appears to happen somewhat commonly (e.g. #260), and is an error in something other than nextest. Define an exit code for this condition and make it an expected error.
Also improve reporting around which target runner in use and where it was defined.

[nextest] better error messages for parsing test lists

---

Cargo.lock
nextest-runner/Cargo.toml
nextest-runner/default-config.toml
nextest-runner/src/config.rs
nextest-runner/src/reporter.rs
nextest-runner/src/reporter/aggregator.rs
nextest-runner/src/runner.rs

this PR shows an opinionated minimal implementation for #213 and it meant to serve as tangible initial input for the design of this feature.
cc @sunshowers

feat: support termination of slow tests

---

cargo-nextest/src/tests_integration/fixtures.rs
fixtures/nextest-tests/.config/nextest.toml
fixtures/nextest-tests/tests/basic.rs
nextest-runner/src/reporter.rs
nextest-runner/src/runner.rs
nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/fixtures.rs

cc @steveeJ -- you might be interested in how I wrote an integration test for this

[nextest-runner] fixes + integration test for slow timeout termination

---

cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
nextest-runner/src/cargo_config.rs
nextest-runner/src/errors.rs
nextest-runner/src/target_runner.rs
nextest-runner/tests/integration/fixtures.rs
nextest-runner/tests/integration/main.rs
nextest-runner/tests/integration/target_runner.rs
nextest-runner/tests/integration/target_triple.rs

Follow https://doc.rust-lang.org/cargo/reference/config.html#buildtarget.
TODO is tests for this.

[nextest-runner] look through env var and cargo configs for target triple

---

cargo-nextest/src/cargo_cli.rs

mirrors https://github.com/rust-lang/cargo/pull/10576

Add `-F` alias for `--features`

---

nextest-runner/src/reporter.rs

If nextest itself is producing colorized output:
* output text as-is
* reset colors at the end
If nextest is not colorized, retain the old behavior.
Fixes #302.

[nextest-runner] don't strip ANSI escape codes in some cases

---

Cargo.lock
cargo-nextest/src/tests_integration/fixtures.rs
nextest-runner/Cargo.toml
nextest-runner/src/helpers.rs
nextest-runner/src/reporter.rs
nextest-runner/src/reporter/aggregator.rs
nextest-runner/src/runner.rs
nextest-runner/tests/integration/fixtures.rs
nextest-runner/tests/integration/target_runner.rs

This will typically be EXCEPTION_ACCESS_VIOLATION for a segfault on Windows.

[nextest-runner] track exception codes on Windows

---

Cargo.lock
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/tests_integration/fixtures.rs
cargo-nextest/src/tests_integration/mod.rs
nextest-filtering/CHANGELOG.md
nextest-filtering/Cargo.toml
nextest-metadata/CHANGELOG.md
nextest-metadata/Cargo.toml
nextest-runner/CHANGELOG.md
nextest-runner/Cargo.toml
nextest-runner/src/list/test_list.rs
nextest-runner/src/test_filter.rs
nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/fixtures.rs
site/src/CHANGELOG.md
site/src/SUMMARY.md
site/src/book/configuration.md
site/src/book/env-vars.md
site/src/book/filter-expressions.md
site/src/book/machine-readable.md
site/src/book/per-test-overrides.md
site/src/book/reusing-builds.md
site/src/book/running.md

Last few commits before we publish new releases of all our projects.

[WIP] [cargo-nextest] prepare for release

---

site/src/book/pre-built-binaries.md

I added cargo-nextest to Homebrew :)

Add Homebrew install instructions

---

nextest-runner/src/cargo_config.rs
nextest-runner/src/target_runner.rs

Do a better job of emulating Cargo.
Fixes #406.

[nextest-runner] fix target runner resolution for relative paths

---

site/src/book/miri.md

The fact that Miri can do this still regularly catches people by surprise, so it seems worth advertising here, if you are okay with that. :)
I also added a link to explain what UB is.

mention Miri's cross-interpretation feature

---

.github/workflows/coverage.yml

Followup to #343 -- clean up diff.
Supersedes and closes #343.

[ci] upload coverage to codecov.io

---

cargo-nextest/src/dispatch.rs

While this is identical to `cargo nextest list -E 'none()'`, it is more intuitive to do it this way (#422).

[cargo-nextest] add cargo nextest run --no-run

---

Cargo.lock
nextest-runner/Cargo.toml
nextest-runner/src/runner.rs

win32job 1.0.2 has Send and Sync impls -- use those.

[nextest-runner] update win32job to get Send and Sync impls

---

Cargo.lock
cargo-nextest/Cargo.toml
nextest-metadata/CHANGELOG.md
nextest-metadata/Cargo.toml
nextest-metadata/src/test_list.rs
nextest-runner/CHANGELOG.md
nextest-runner/Cargo.toml
nextest-runner/src/cargo_config.rs
nextest-runner/src/list/binary_list.rs
nextest-runner/src/list/rust_build_meta.rs
nextest-runner/src/list/test_list.rs
site/src/CHANGELOG.md

A couple of final fixes, and then get a release ready.

prepare releases

---

Cargo.lock

[target-spec] update to 1.1.0

---

cargo-nextest/src/dispatch.rs
nextest-runner/src/reporter.rs

Add option to hide progress bar

---

cargo-nextest/src/dispatch.rs
nextest-runner/src/config.rs
site/help-text/run-help.txt

Added support for negative jobs values

---

nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/fixtures.rs
nextest-runner/tests/integration/target_runner.rs

As per https://github.com/nextest-rs/nextest/pull/534#issuecomment-1254414438.

refactor: `set_rustflags` -> `set_env_vars`

---

Cargo.lock
cargo-nextest/Cargo.toml
cargo-nextest/src/cargo_cli.rs
cargo-nextest/src/dispatch.rs
cargo-nextest/src/output.rs
cargo-nextest/src/reuse_build.rs
cargo-nextest/src/tests_integration/fixtures.rs
cargo-nextest/src/tests_integration/mod.rs
nextest-filtering/Cargo.toml
nextest-runner/src/errors.rs
nextest-runner/src/reporter.rs
nextest-runner/src/test_filter.rs
site/help-text/archive-help.txt
site/help-text/list-help.txt
site/help-text/run-help.txt
workspace-hack/Cargo.toml

Will land this after clap v4 stabilizes.

upgrade to clap 4.0

---

nextest-runner/src/runner.rs

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

Refactor: Simplify by using `try_join(stdout_fut, stderr_fut)`

---

nextest-runner/src/config.rs
nextest-runner/src/runner.rs

This also skips output of the TERMINATING message when `grace-period = "0s"`:
```
Starting 6 tests across 2 binaries
TIMEOUT [   2.012s] unicode-xid::exhaustive_tests all_valid_chars_do_not_panic_for_is_xid_continue
--- STDOUT:              unicode-xid::exhaustive_tests all_valid_chars_do_not_panic_for_is_xid_continue ---
running 1 test
test all_valid_chars_do_not_panic_for_is_xid_continue ... 
TIMEOUT [   2.012s] unicode-xid::exhaustive_tests all_valid_chars_do_not_panic_for_is_xid_start
--- STDOUT:              unicode-xid::exhaustive_tests all_valid_chars_do_not_panic_for_is_xid_start ---
running 1 test
test all_valid_chars_do_not_panic_for_is_xid_start ... 
PASS [   0.802s]                   unicode-xid tests::test_is_not_xid_continue
PASS [   0.782s]                   unicode-xid …
```

[nextest-runner] add a shutdown grace period, with special handling for no grace

---

nextest-runner/src/config.rs

fix https://github.com/nextest-rs/nextest/issues/622

fix: handle profile with 0 retries

---

nextest-runner/src/double_spawn.rs

This prevents races in case the binary gets moved out from underneath us -- it always refers to the current exe.

[nextest-runner] use /proc/self/exe directly on Linux

---

.github/workflows/ci.yml
.github/workflows/release.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/sunshowers/nextest/pull/655).
* __->__ #655
[ci] switch to beta Rust to pick up process spawning improvements

[ci] switch to beta Rust to pick up process spawning improvements

---

cargo-nextest/src/cargo_cli.rs
site/help-text/archive-help.txt
site/help-text/list-help.txt
site/help-text/run-help.txt

These are cargo test options to run unit tests that live in examples.

cli: support --example EXAMPLE and --examples

---

cargo-nextest/src/dispatch.rs

This PR aims to fix #699 
It solved my issue but I don't know if it's expected to work that way...
Let me know !
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

fix: missing graph_with_deps for run

---

site/src/book/junit.md

This had me confused b/c I tried adding the profile to my Cargo.toml instead of my nextest.toml

Doc improvement: junit configuration

---

nextest-runner/src/config.rs

We're going to use them in the future.

[nextest-runner] stash original filter and platform expressions for overrides

---

nextest-runner/src/config.rs

Also add tests to ensure everything is deserialized correctly.
Fixes #762.

[nextest-runner] fix deserialization of overrides.leak-timeout

---

nextest-metadata/src/test_list.rs
nextest-runner/src/list/test_list.rs

Closes https://github.com/nextest-rs/nextest/issues/846

metadata: Use `--mesage-format` instead of  `--format`

---

nextest-runner/src/config/overrides.rs
nextest-runner/src/config/test_helpers.rs
nextest-runner/src/reporter.rs

Move some code around, and a small fix.

[nextest-runner] even more setup script prep

---

.github/workflows/ci.yml
.github/workflows/docs.yml

As pointed out in https://github.com/nextest-rs/nextest/pull/1005#issuecomment-1741747433.

Switch to install-action for crates where binaries are available

---

.github/workflows/coverage.yml

[ci] also generate coverage report for doctests

---

Cargo.lock
Cargo.toml
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/output.rs
nextest-runner/Cargo.toml
nextest-runner/src/helpers.rs
nextest-runner/src/indenter.rs
nextest-runner/src/lib.rs
nextest-runner/src/list/binary_list.rs
nextest-runner/src/list/output_format.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/reporter.rs
nextest-runner/src/show_config/test_groups.rs
nextest-runner/src/write_str.rs

Started writing some code that ended up not going anywhere, but all of this seems generally useful.

a few bits of cleanup

---

integration-tests/tests/integration/main.rs
nextest-runner/src/config/archive_include.rs
nextest-runner/src/config/mod.rs
nextest-runner/src/config/track_default.rs
nextest-runner/src/reuse_build/archive_reporter.rs
nextest-runner/src/reuse_build/archiver.rs

Followup to #1344.
If a loop happens somehow, we'll want to exit early.

[nextest-runner] add optional "depth" param, limit archive recursion to 8 by default

---

nextest-runner/src/runner.rs

Per discussion with @sunshowers on Mastodon.

[nextest-runner] Remove load-bearing wildcard.

---

cargo-nextest/src/dispatch.rs
nextest-runner/src/helpers.rs
nextest-runner/src/reporter.rs
nextest-runner/src/runner.rs
nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/target_runner.rs

Add warnings for:
* https://github.com/nextest-rs/nextest/issues/1639
* If some tests were not run (anecdotally, this has been a source of confusion)

[nextest-runner] add warnings in some cases

---

nextest-runner/src/reporter/displayer.rs

Many CI systems can't handle multi-line colors -- they reset the color after each line. Within nextest, we can be smarter about this.

[nextest-runner] color each line in multi-line highlights separately

---

.config/nextest.toml
.github/workflows/ci.yml

The Trunk team has graciously agreed to help out with nextest integration, so let's start uploading JUnit reports to it.

[ci] try uploading JUnit results to Trunk

---

Cargo.lock
Cargo.toml
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
cargo-nextest/src/helpers.rs
cargo-nextest/src/output.rs
cargo-nextest/src/reuse_build.rs
cargo-nextest/src/update.rs
nextest-runner/Cargo.toml
nextest-runner/src/cargo_config/discovery.rs
nextest-runner/src/config/config_impl.rs
nextest-runner/src/double_spawn.rs
nextest-runner/src/list/binary_list.rs
nextest-runner/src/list/rust_build_meta.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/platform.rs
nextest-runner/src/reuse_build/archiver.rs
nextest-runner/src/runner.rs
nextest-runner/src/rustc_cli.rs
nextest-runner/src/update.rs
workspace-hack/Cargo.toml

About time we switched over.
Write our own simple formatter to match the existing formatting.

[meta] switch to tracing

---

nextest-runner/src/config/scripts.rs
nextest-runner/src/runner.rs

Add some wrapper structs to pass in arguments. We're going to be adding even more arguments in the future, and these wrappers make that job significantly easier.

[nextest-runner] tackle some of the too_many_arguments clippy lints

---

Cargo.lock
cargo-nextest/src/dispatch.rs
cargo-nextest/src/errors.rs
fixture-data/src/models.rs
fixture-data/src/nextest_tests.rs
fixtures/nextest-tests/.config/nextest.toml
integration-tests/Cargo.toml
integration-tests/tests/integration/fixtures.rs
integration-tests/tests/integration/main.rs
integration-tests/tests/integration/snapshots/integration__list_with_default_set_basic.snap
integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_all.snap
integration-tests/tests/integration/snapshots/integration__list_with_default_set_expr_default.snap
nextest-runner/src/config/config_impl.rs
nextest-runner/src/config/mod.rs
nextest-runner/src/config/overrides.rs
nextest-runner/src/config/scripts.rs
nextest-runner/src/errors.rs
nextest-runner/src/reporter/aggregator.rs
nextest-runner/src/reporter/displayer.rs
nextest-runner/src/reuse_build/archiver.rs
nextest-runner/src/runner.rs
nextest-runner/src/show_config/test_groups.rs
site/src/changelog.md
site/src/docs/configuration/per-test-overrides.md
site/src/docs/running.md

See https://github.com/nextest-rs/nextest/discussions/1869.

Add per-platform default filters

---

nextest-runner/src/runner.rs

In upcoming work we're going to add the ability to query test tasks. For a coherent UX it's important that what the context reports is consistent with tests. (For example, if the displayer hasn't shown a test as started, it is surprising to see output for it.)
In order to achieve that, move away from broadcast channels towards centralizing all channel management code in `CallbackContext`. With this change, execution units now ensure that the callback context is synced up with them before proceeding.

[nextest-runner] centralize channel management in CallbackContext

---

nextest-runner/src/reporter/displayer.rs

This has to be done with some care. There can be multiple reasons for showing or hiding the bar (e.g. run paused in the middle of running a setup script with no-capture) -- ensure that we track all of them and don't just use whatever we saw last.

[nextest-runner] hide/show progress bar around run paused/continued

---

Cargo.lock
Cargo.toml
nextest-runner/Cargo.toml
nextest-runner/src/config/scripts.rs
nextest-runner/src/errors.rs
nextest-runner/src/runner.rs

Wasn't overly satisfied with the upstream one, in particular with issues around indentation.

[nextest-runner] write our own DisplayErrorChain

---

nextest-runner/src/reporter/displayer.rs

We're going to add an alternative spec in upcoming work.

[nextest-runner] factor out code to display output into specs

---

nextest-runner/src/runner.rs

This avoids a potential race between units exiting and sender_strong_count being called.

[nextest-runner] make broadcast_request return a count

---

cargo-nextest/src/dispatch.rs
nextest-runner/src/config/max_fail.rs
nextest-runner/src/runner/dispatcher.rs
nextest-runner/src/runner/imp.rs

Fixes https://github.com/nextest-rs/nextest/issues/1955.

[nextest-runner] a couple of fixes for max-fail handling

---

nextest-runner/src/config/archive.rs

I realized that we weren't joining directories like `"."` properly -- we should join component-by-component. Also ensure the same way to join relative paths across platforms.

[nextest-runner] join archive extra dirs consistently

---

nextest-runner/src/config/overrides.rs
nextest-runner/src/config/test_helpers.rs

Previous versions of target-spec didn't deserialize the `target_family` field correctly.

[nextest-runner] add test for custom platforms + cfg(unix)

---

site/mkdocs.yml
site/src/docs/design/architecture/input-handling.md
site/src/docs/design/architecture/runner-loop.md
site/src/docs/design/architecture/signal-handling.md
site/src/docs/reporting.md

This is a somewhat tricky topic, so I thought I'd write up the design decisions here.

[site] add design doc about input handling

---

nextest-runner/src/cargo_config/discovery.rs
nextest-runner/src/config/config_impl.rs
nextest-runner/src/config/overrides.rs
nextest-runner/src/config/retry_policy.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/reporter/displayer/unit_output.rs
nextest-runner/src/signal.rs
nextest-runner/src/update.rs

[meta] update to Rust 1.84

---

nextest-runner/src/reuse_build/archiver.rs

Fix for the bug report in #2067

fix: support for non-multithread libzstd (#2067)

---

Cargo.lock
Cargo.toml
nextest-runner/src/config/config_impl.rs
workspace-hack/Cargo.toml

Requires a little error message tweaking.

[nextest-runner] update to config 0.15.6

---

cargo-nextest/src/dispatch.rs
fixtures/nextest-tests/scripts/my-script.bat
fixtures/nextest-tests/scripts/my-script.sh
fixtures/nextest-tests/tests/basic.rs
integration-tests/src/env.rs
nextest-runner/src/config/scripts.rs
nextest-runner/src/list/test_list.rs
nextest-runner/src/runner/executor.rs
nextest-runner/src/test_command.rs
nextest-runner/tests/integration/basic.rs
nextest-runner/tests/integration/fixtures.rs
nextest-runner/tests/integration/target_runner.rs

Per https://github.com/nextest-rs/nextest/issues/978#issuecomment-2642067095.

add NEXTEST_PROFILE to test and script environments

---

nextest-runner/src/config/overrides.rs

[nextest-runner] fix infinite recursion with platform-specific overrides

---

cargo-nextest/src/dispatch.rs

Specifically, in the case of environment variables that conflict with CLI args, it's better to warn rather than fail to compile.
I wish I could obtain the source of where a CLI arg's value came from, but clap doesn't appear to have a way to do that.
Fixes #2261.

[cargo-nextest] warn rather than fail with --no-run

---

nextest-runner/src/input.rs

There's a difference between stdin being a terminal and nextest actually being in control of the terminal. Also do the latter check on Unix.
On Windows, this doesn't appear to be necessary.
This makes watchexec + nextest no longer hang. I tested and watchexec + nextest don't hang on Windows either.

[nextest-runner] on Unix, check that nextest controls the terminal

---

nextest-runner/src/input.rs

[nextest-runner] add debug logging for input handler

---

Cargo.toml
nextest-runner/src/list/test_list.rs
nextest-runner/src/runner/executor.rs

Some improvements with made #2316 easier to debug.
I'd like to also write more detailed logs into a log file at some point.

[nextest-runner] debugging improvements for #2316

---

site/mkdocs.yml
site/src/docs/ci-features/partitioning.md

[site] fix social card for partitioning runs page

---

cargo-nextest/src/double_spawn.rs
cargo-nextest/src/errors.rs
integration-tests/src/nextest_cli.rs
nextest-runner/src/double_spawn.rs
nextest-runner/src/reporter/aggregator/junit.rs
nextest-runner/src/reporter/structured/libtest.rs
nextest-runner/src/reuse_build/archiver.rs
nextest-runner/src/runner/dispatcher.rs
nextest-runner/src/update.rs
nextest-runner/src/write_str.rs

Consists of illumos posix_spawn fixes in particular.

[meta] update to Rust 1.87

---

integration-tests/src/nextest_cli.rs

Tee nextest's stdout to the test's stdout, and nextest's stderr to the test's stderr.

[integration-tests] tee nextest output rather than merely capturing it

---

Cargo.lock
Cargo.toml
cargo-nextest/Cargo.toml
cargo-nextest/src/dispatch.rs
nextest-runner/src/errors.rs
nextest-runner/src/helpers.rs
nextest-runner/src/list/output_format.rs
nextest-runner/src/reporter/aggregator/junit.rs
nextest-runner/src/reporter/displayer/formatters.rs
nextest-runner/src/reporter/displayer/imp.rs
nextest-runner/src/reporter/displayer/progress.rs
nextest-runner/src/reporter/displayer/snapshots/nextest_runner__reporter__displayer__imp__tests__final_status_output.snap
nextest-runner/src/reporter/displayer/snapshots/nextest_runner__reporter__displayer__imp__tests__info_response_output.snap
nextest-runner/src/reporter/events.rs
nextest-runner/src/reporter/structured/libtest.rs
nextest-runner/src/runner/dispatcher.rs
nextest-runner/src/runner/executor.rs
nextest-runner/src/runner/imp.rs
nextest-runner/src/runner/internal_events.rs
nextest-runner/tests/integration/fixtures.rs

Add support for running stress tests, one run at a time.

add basic support for stress testing

---

cargo-nextest/src/cargo_cli.rs

Always forward --config args to cargo invocations
